### ISSUE TITLE
Incorrect Response When Out of Money

### ISSUE THREAD

**Issue by eightysixed** [Senso/eos-bot#2]
The script is no longer reporting correctly when trying to buy items when you've run out of money (towards the end of a large-buy run, etc.). It used to display "Not enough money" or something similar. Now I'm seeing, for example, the following:

Bought 1250 of sunglasses(s) at $141,925.00
            Cost: 113.54
            Avg price: 240.0
            Will sell at: $227.08

```
Sweater is Out of Stock.
    Searching page 1 of import category for Sweater
    Found Sweater
    Found Sweater
    Searching page 2 of import category for Sweater
    Searching page 3 of import category for Sweater
    No more listings for Sweater

T-Shirt is Out of Stock.
    Searching page 1 of import category for T-Shirt
    Found T-Shirt
```

Bought 1250 of t-shirt(s) at $58,687.50
            Cost: 46.95
            Avg price: 121.0
            Will sell at: $93.9

```
Wallet is Out of Stock.
    Searching page 1 of import category for Wallet
    Found Wallet
    Found Wallet
    Searching page 2 of import category for Wallet
    No more listings for Wallet

Wedding Dress is Out of Stock.
    Searching page 1 of import category for Wedding Dress
    Searching page 2 of import category for Wedding Dress
    Found Wedding Dress
    Found Wedding Dress
    Searching page 3 of import category for Wedding Dress
    No more listings for Wedding Dress

Wig is Out of Stock.
    Searching page 1 of import category for Wig
    Found Wig
    Found Wig
    Searching page 2 of import category for Wig
    No more listings for Wig

Wool Coat is Out of Stock.
    Searching page 1 of import category for Wool Coat
    Searching page 2 of import category for Wool Coat
    Found Wool Coat
    Found Wool Coat
    Searching page 3 of import category for Wool Coat
    No more listings for Wool Coat
```

In that example, you can see I had enough money to buy cheaper items, such as Sunglasses and T-Shirts, but not enough to buy some others, and it's failing with 'No more listings for X' even though it's been found but can't be bought due to lack of available funds.

**Comment by Senso** [comment]
All right, I will be taking a look at this pretty soon.
